package app.menosan.analytics

import app.menosan.reports.analyticsTaxonomy
import app.menosan.taxonomy.Taxonomy
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Runs `aggregate`, `findHotspots`, `compare`, and `measureImpact` against `docs/analytics-test-vectors.json`,
 * the file Android's port must also pass (plan §5.7).
 *
 * After an intentional rule change (with an ALGORITHM_VERSION bump), regenerate the expected blocks with
 * `REGEN_ANALYTICS_VECTORS=true ./gradlew test --tests '*AnalyticsVectorsTest*'`, review the diff by hand,
 * and copy the file to menosan-android.
 */
class AnalyticsVectorsTest {
    private val file = File("docs/analytics-test-vectors.json")
    private val taxonomy = Taxonomy.loadDefault()

    @Test
    fun `all four functions match the shared test vectors`() {
        val vectors = VectorJson.decodeFromString(VectorFile.serializer(), file.readText())
        if (System.getenv("REGEN_ANALYTICS_VECTORS") == "true") regenerate(vectors)

        val current = VectorJson.decodeFromString(VectorFile.serializer(), file.readText())
        assertEquals(ALGORITHM_VERSION, current.algorithmVersion, "Bump the vectors together with ALGORITHM_VERSION")
        assertEquals(taxonomy.version, current.taxonomyVersion)
        assertTrue(current.cases.size >= 14, "Plan §9 BE-3 asks for at least 14 cases")
        assertEquals(current.cases.size, current.cases.map { it.name }.toSet().size, "Case names must be unique")
        for (case in current.cases) {
            val expected = assertNotNull(case.expected, "${case.name}: expected is missing; regenerate the vectors")
            assertEquals(expected, run(case), case.name)
        }
    }

    private fun run(case: VectorCase): Expected {
        val tax = taxonomy.analyticsTaxonomy()
        val stats = aggregate(case.entries.map { EntryInput(it.subcategory, it.quantity) }, tax)
        val previous = aggregate(case.previousEntries.map { EntryInput(it.subcategory, it.quantity) }, tax)
        return Expected(
            stats = stats,
            hotspots = findHotspots(stats, tax),
            comparison = compare(stats, previous, case.previousWeekStart),
            impacts = measureImpact(case.adoptions, stats),
        )
    }

    private fun regenerate(vectors: VectorFile) {
        val updated = vectors.copy(
            algorithmVersion = ALGORITHM_VERSION,
            taxonomyVersion = taxonomy.version,
            about = ABOUT,
            cases = vectors.cases.map { it.copy(expected = run(it)) },
        )
        file.writeText(VectorJson.encodeToString(VectorFile.serializer(), updated) + "\n")
    }

    @Serializable
    data class VectorFile(val algorithmVersion: Int, val taxonomyVersion: Int, val about: String, val cases: List<VectorCase>)

    @Serializable
    data class VectorCase(
        val name: String,
        val description: String,
        val previousWeekStart: String = "2026-09-20",
        val previousEntries: List<VectorEntry> = emptyList(),
        val adoptions: List<AdoptionInput> = emptyList(),
        val entries: List<VectorEntry>,
        val expected: Expected? = null,
    )

    @Serializable
    data class VectorEntry(val subcategory: String, val quantity: Int)

    @Serializable
    data class Expected(val stats: WeeklyStats, val hotspots: List<Hotspot>, val comparison: Comparison?, val impacts: List<Impact>)

    private companion object {
        val VectorJson = Json {
            prettyPrint = true
            encodeDefaults = true
            explicitNulls = true
        }

        const val ABOUT =
            "Shared test vectors for the Menosan analytics (DEVELOPMENT_PLAN §5.1-§5.4), used by menosan-api and menosan-android. " +
                "Subcategory codes refer to taxonomy.json (taxonomyVersion). For each case: " +
                "stats = aggregate(entries); hotspots = findHotspots(stats); " +
                "comparison = compare(stats, aggregate(previousEntries), previousWeekStart), where an empty previousEntries means nothing was logged in W-1; " +
                "impacts = measureImpact(adoptions, stats), where adoptions were made on report W-1. " +
                "Generated by AnalyticsVectorsTest in menosan-api; do not edit expected blocks by hand."
    }
}
