-- V3: curated intervention library (plan §6.1, §6.4). Owned by BE-4.
-- Gemini may only pick from and annotate these rows, never invent new ones (NFR12).
-- At least 3 active items per non-SPECIAL subcategory; none for SPECIAL (NFR13).
-- Codes are stable identifiers. To change content later, add a new migration (UPDATE / deactivate); never edit this file.

INSERT INTO interventions (code, subcategory_code, type, title, description, how_to, cost_level, effort) VALUES

-- BIO_FOOD_LEFTOVERS
('BIO_FOOD_LEFTOVERS_MEASURE_RICE', 'BIO_FOOD_LEFTOVERS', 'REDUCE',
 'Measure rice by headcount before cooking',
 'Try cooking rice by headcount this week: about one cup of uncooked rice per person eating. Less leftover rice also means less rice to buy.',
 ARRAY['Count who is eating at home for the meal.',
       'Use one measuring cup (or the same can or tabo each time) per person.',
       'If rice runs out, cook a small extra batch instead of a big pot "just in case".'],
 'SAVES_MONEY', 'LOW'),
('BIO_FOOD_LEFTOVERS_REMIX_MEALS', 'BIO_FOOD_LEFTOVERS', 'REUSE',
 'Turn leftovers into the next meal',
 'Leftover rice and ulam can become the next breakfast or baon: sinangag, lugaw, torta, or fried rice with leftover ulam. It saves you one meal''s worth of cooking.',
 ARRAY['Cover and refrigerate leftovers within 2 hours of cooking.',
       'Fry day-old rice with garlic for sinangag, or boil it into lugaw.',
       'Mix leftover ulam with egg for torta, or toss it into fried rice.'],
 'SAVES_MONEY', 'LOW'),
('BIO_FOOD_LEFTOVERS_SMALL_PORTIONS', 'BIO_FOOD_LEFTOVERS', 'PREVENT',
 'Serve small first portions, then get seconds',
 'Try serving smaller first portions and letting everyone get seconds. Food left in the pot keeps for the next meal, while food left on a plate usually does not.',
 ARRAY['Serve half portions for kids and a normal first scoop for adults.',
       'Keep the pot covered on the table or stove for seconds.',
       'Store what is left in the pot right after the meal.'],
 'FREE', 'LOW'),
('BIO_FOOD_LEFTOVERS_SHARE_EXTRA', 'BIO_FOOD_LEFTOVERS', 'REUSE',
 'Share extra food with neighbors or animals',
 'When you cooked more than your household can eat, share it with neighbors or relatives the same day. Safe plain scraps like rice can also go to pets or backyard animals.',
 ARRAY['Set aside extra food while it is still fresh, not after it sits out.',
       'Offer it to a neighbor or relative to take home.',
       'Give only safe scraps to animals: no cooked bones for dogs, and nothing spoiled.'],
 'FREE', 'LOW'),

-- BIO_SPOILED_FOOD
('BIO_SPOILED_FOOD_CHECK_BEFORE_MARKET', 'BIO_SPOILED_FOOD', 'PREVENT',
 'Check the fridge before going to the palengke',
 'Before your next palengke trip, take one minute to check the fridge and shelves, then write a short list. You buy only what you will use, and nothing gets forgotten at the back.',
 ARRAY['Look in the fridge, freezer, and pantry shelf before leaving.',
       'Write a short list, or take a phone photo of what you still have.',
       'Buy only what is on the list for the next few days.'],
 'SAVES_MONEY', 'LOW'),
('BIO_SPOILED_FOOD_OLDEST_FIRST', 'BIO_SPOILED_FOOD', 'PREVENT',
 'Oldest first: put older food in front',
 'Try moving older food to the front of the fridge or shelf and new purchases to the back. The food that will spoil first is then the food you see first.',
 ARRAY['When you unpack groceries, move what is already there to the front.',
       'Keep one front spot or container for "eat first" food.',
       'Check that spot before you cook each day.'],
 'FREE', 'LOW'),
('BIO_SPOILED_FOOD_BUY_FOR_FEW_DAYS', 'BIO_SPOILED_FOOD', 'REDUCE',
 'Buy perishables for 2-3 days at a time',
 'Buy fish, vegetables, and bread for 2-3 days at a time instead of a whole week. Smaller, more frequent buys spoil less and fit a tight budget.',
 ARRAY['Plan simple meals for the next 2-3 days only.',
       'Buy perishables for those meals, and keep rice, eggs, and canned goods as backup.',
       'Pick up more on your next palengke or sari-sari store trip.'],
 'SAVES_MONEY', 'MEDIUM'),
('BIO_SPOILED_FOOD_RESCUE_RIPE_FRUIT', 'BIO_SPOILED_FOOD', 'REUSE',
 'Turn very ripe fruit into merienda',
 'Overripe bananas and soft fruit are perfect for cooking. Turn them into turon, maruya, or banana cue before they spoil.',
 ARRAY['Check the fruit basket every day or two.',
       'Set aside fruit that is soft or getting spots.',
       'Cook it into turon, maruya, or banana cue for merienda that day.'],
 'SAVES_MONEY', 'LOW'),

-- BIO_PEELS_SCRAPS
('BIO_PEELS_SCRAPS_COMPOST_PIT', 'BIO_PEELS_SCRAPS', 'REUSE',
 'Bury peels in a small compost pit or pot',
 'Peels and scraps make free fertilizer for plants. Dig a small pit in the yard, or use a big pot or old pail, and bury them under a layer of soil.',
 ARRAY['Pick a spot away from the house, or use an old pail or large pot.',
       'Drop in peels and scraps, then cover them with a handful of soil or dry leaves.',
       'Keep adding, and after a few weeks use the soil for your plants.'],
 'FREE', 'MEDIUM'),
('BIO_PEELS_SCRAPS_USE_MORE_PRODUCE', 'BIO_PEELS_SCRAPS', 'REDUCE',
 'Use more of the vegetables you buy',
 'Many parts we usually throw away are good to eat. Cook kangkong stems, malunggay stalks, and vegetable ends into dishes or a simple broth.',
 ARRAY['Chop kangkong stems finely and saute them with the leaves.',
       'Keep clean vegetable ends in a container in the fridge.',
       'Boil them with water and salt for a broth for sinabawan or lugaw.'],
 'SAVES_MONEY', 'LOW'),
('BIO_PEELS_SCRAPS_GIVE_TO_ANIMAL_KEEPER', 'BIO_PEELS_SCRAPS', 'REUSE',
 'Give scraps to a neighbor with pigs or chickens',
 'If a neighbor keeps pigs, chickens, or ducks, your vegetable scraps can become feed. Ask if they want them before you throw them out.',
 ARRAY['Ask neighbors if anyone keeps animals and would like scraps.',
       'Keep a covered container for scraps, separate from other trash.',
       'Drop it off every day or two while it is still fresh.'],
 'FREE', 'LOW'),

-- BIO_YARD_WASTE
('BIO_YARD_WASTE_LEAF_MULCH', 'BIO_YARD_WASTE', 'REUSE',
 'Use dry leaves as mulch around plants',
 'Spread dry leaves around the base of your plants instead of throwing them out. They keep the soil moist, so you water less.',
 ARRAY['Rake dry leaves into a pile.',
       'Spread a thin layer around plants, a little away from the stems.',
       'Add more leaves as the layer breaks down.'],
 'FREE', 'LOW'),
('BIO_YARD_WASTE_COMPOST_PILE', 'BIO_YARD_WASTE', 'REUSE',
 'Start a simple compost pile in the yard',
 'Pick a corner of the yard and pile leaves, grass, and twigs there. In a few weeks it turns into soil you can use for plants.',
 ARRAY['Choose a shaded corner away from the house.',
       'Pile yard waste there, breaking big twigs into small pieces.',
       'Mix in food peels and turn the pile once a week.'],
 'FREE', 'MEDIUM'),
('BIO_YARD_WASTE_LEAVE_CLIPPINGS', 'BIO_YARD_WASTE', 'REDUCE',
 'Leave grass clippings on the ground',
 'After cutting grass, leave the clippings where they fall. They break down in days and feed the soil for free.',
 ARRAY['Cut grass when it is dry, a little at a time.',
       'Leave short clippings spread out on the ground.',
       'Rake up only thick clumps and put them under plants.'],
 'FREE', 'LOW'),

-- BIO_OTHER
('BIO_OTHER_COMPOST_IF_PLANT_BASED', 'BIO_OTHER', 'REUSE',
 'Compost it if it is plant- or food-based',
 'If the item comes from plants or food, like coconut husk or corn cobs, it can go into a compost pit or pile. Break it into smaller pieces so it breaks down faster.',
 ARRAY['Check that it is plant- or food-based, with no plastic attached.',
       'Break or cut it into smaller pieces.',
       'Add it to a compost pit, pile, or pot and cover it with soil.'],
 'FREE', 'LOW'),
('BIO_OTHER_NAME_IT', 'BIO_OTHER', 'PREVENT',
 'Note what it was so Menosan can suggest more',
 'Next time, give the item a short, specific name and pick the closest subcategory when logging. Menosan can then suggest something that fits better.',
 ARRAY['When logging, write what the item is, like "coconut husk" or "corn cobs".',
       'Choose the closest subcategory instead of Other when one fits.'],
 'FREE', 'LOW'),
('BIO_OTHER_ASK_NEIGHBOR', 'BIO_OTHER', 'REUSE',
 'Ask a neighbor who gardens or keeps animals',
 'Some biodegradable items, like coconut husk or corn cobs, are useful to gardeners or animal keepers. Ask around before throwing them out.',
 ARRAY['Ask neighbors or relatives who garden or keep animals.',
       'Keep the items dry and separate until you hand them over.'],
 'FREE', 'LOW'),

-- REC_PET_BOTTLES
('REC_PET_BOTTLES_REFILL_OWN_BOTTLE', 'REC_PET_BOTTLES', 'PREVENT',
 'Refill a bottle you own with water from home',
 'Fill a bottle you already have with water from home before going out. You skip buying bottled water and save money each time.',
 ARRAY['Pick one sturdy bottle you already own for each person who goes out.',
       'Fill it with drinking water the night before or before leaving.',
       'Refill it at home, school, or work water stations when you can.'],
 'SAVES_MONEY', 'LOW'),
('REC_PET_BOTTLES_SHARE_BIG_BOTTLE', 'REC_PET_BOTTLES', 'REDUCE',
 'Share one 1.5 L bottle instead of small ones',
 'For family drinks, one 1.5 L bottle shared in glasses usually costs less than several small bottles. It also means fewer bottles to throw out.',
 ARRAY['Compare the price per liter of big and small bottles at the store.',
       'Buy one big bottle for the family meal or merienda.',
       'Pour into glasses and keep the rest cold with the cap on.'],
 'SAVES_MONEY', 'LOW'),
('REC_PET_BOTTLES_REUSE_FOR_STORAGE', 'REC_PET_BOTTLES', 'REUSE',
 'Reuse clean bottles for water, oil, or suka',
 'Wash and keep sturdy bottles for drinking water, or bring them when buying cooking oil or suka tingi. Label them so everyone knows what is inside.',
 ARRAY['Wash bottles with soap and water, then let them dry upside down.',
       'Label each one: water, oil, or suka.',
       'Bring one to the sari-sari store when buying oil or suka by the bottle.'],
 'FREE', 'LOW'),

-- REC_RIGID_PLASTICS
('REC_RIGID_PLASTICS_REUSE_TUBS', 'REC_RIGID_PLASTICS', 'REUSE',
 'Reuse tubs and containers for storage and baon',
 'Ice cream tubs and food containers you already have work well for leftovers, baon, and pantry storage. Keep a few clean ones ready.',
 ARRAY['Wash tubs and lids and keep them together.',
       'Use them for leftovers, baon, or storing rice, sugar, and snacks.',
       'Pass extra ones to neighbors or relatives who need containers.'],
 'FREE', 'LOW'),
('REC_RIGID_PLASTICS_REFILL_STATION', 'REC_RIGID_PLASTICS', 'REDUCE',
 'Refill detergent or dishwashing liquid',
 'Bring an old detergent or dishwashing-liquid bottle to a refill station and buy only the amount you need. Refills usually cost less than a new bottle.',
 ARRAY['Find a refill station at the palengke, a sari-sari store, or a grocery.',
       'Rinse your old bottle and bring it along.',
       'Ask for the amount your budget allows this week.'],
 'SAVES_MONEY', 'LOW'),
('REC_RIGID_PLASTICS_BRING_CONTAINER', 'REC_RIGID_PLASTICS', 'PREVENT',
 'Bring a container for ulam or wet goods',
 'Bring a container when buying ulam, fish, or meat at the palengke or carinderia. The vendor fills it directly, and you skip the extra plastic tub.',
 ARRAY['Keep a clean container with a lid in your market bag.',
       'Hand it to the vendor before they pack your order.',
       'Wash it at home and put it back in the bag.'],
 'FREE', 'LOW'),

-- REC_PAPER_CARDBOARD
('REC_PAPER_CARDBOARD_NO_RECEIPT', 'REC_PAPER_CARDBOARD', 'PREVENT',
 'Skip printed receipts you do not need',
 'When you do not need proof of purchase, say "no receipt, thanks" or choose an e-receipt. Small slips add up over a week.',
 ARRAY['Decide which purchases really need a receipt, like appliances with a warranty.',
       'For small buys, say "no receipt, thanks".',
       'Choose an e-receipt or SMS confirmation when the store offers one.'],
 'FREE', 'LOW'),
('REC_PAPER_CARDBOARD_REUSE_BOXES_PAPER', 'REC_PAPER_CARDBOARD', 'REUSE',
 'Keep boxes and use paper backs as scratch paper',
 'Keep sturdy boxes for storage and moving things. Use the blank backs of papers as scratch paper for lists or kids'' schoolwork.',
 ARRAY['Flatten good boxes and store them behind a cabinet or under a bed.',
       'Keep a small pile of one-sided papers near the table.',
       'Use them for shopping lists, notes, and schoolwork practice.'],
 'FREE', 'LOW'),
('REC_PAPER_CARDBOARD_DECLINE_FLYERS', 'REC_PAPER_CARDBOARD', 'PREVENT',
 'Decline flyers and extra paper bags',
 'Politely say no to flyers you will not read and to paper bags for items you can carry. It is one less thing to throw away at home.',
 ARRAY['Say "no thanks" to flyers at malls and stores.',
       'Carry small purchases in your own bag instead of a paper bag.',
       'Reuse any paper bags you do get on your next shopping trip.'],
 'FREE', 'LOW'),

-- REC_GLASS
('REC_GLASS_REUSE_JARS', 'REC_GLASS', 'REUSE',
 'Reuse jars for food, atchara, or spices',
 'Clean glass jars are great for storing food, homemade atchara, spices, or coffee and sugar bought takal. They keep food fresh and pests out.',
 ARRAY['Wash jars and lids with soap, then dry them fully.',
       'Soak them in warm water to remove the labels.',
       'Use them for spices, sugar, coffee, or pickles.'],
 'FREE', 'LOW'),
('REC_GLASS_RETURNABLE_BOTTLES', 'REC_GLASS', 'PREVENT',
 'Choose returnable-bottle softdrinks',
 'At the sari-sari store, choose softdrinks in returnable glass bottles. The bottle goes back to the store, and your deposit comes back to you.',
 ARRAY['Ask the store for the returnable-bottle version.',
       'Keep empty bottles in one spot at home.',
       'Bring them back on your next trip to get the deposit or swap them for full ones.'],
 'SAVES_MONEY', 'LOW'),
('REC_GLASS_REUSE_BOTTLES', 'REC_GLASS', 'REUSE',
 'Reuse glass bottles for water, oil, or refills',
 'Sturdy glass bottles can hold cold drinking water, cooking oil, or tingi refills. Glass is easy to clean and lasts a long time.',
 ARRAY['Wash bottles well and let them dry upside down.',
       'Use one for cold drinking water in the fridge.',
       'Bring one when buying oil, suka, or toyo tingi.'],
 'FREE', 'LOW'),

-- REC_METAL_CANS
('REC_METAL_CANS_SWAP_FRESH_DISH', 'REC_METAL_CANS', 'REDUCE',
 'Swap one canned meal a week for a fresh dish',
 'Try replacing one canned meal this week with a simple fresh dish like monggo, eggs, or ginisang gulay. Per serving, it is often cheaper than canned meat.',
 ARRAY['Pick one day this week to skip the canned ulam.',
       'Choose an easy dish: ginisang monggo, torta, or ginisang gulay.',
       'Compare the cost with your usual canned meal.'],
 'SAVES_MONEY', 'MEDIUM'),
('REC_METAL_CANS_REUSE_CANS', 'REC_METAL_CANS', 'REUSE',
 'Use clean cans as pots, scoops, or containers',
 'Clean cans make free plant pots, rice scoops, and holders for pens or utensils. Smooth the edges first to keep hands safe.',
 ARRAY['Wash the can and remove the label.',
       'Press down any sharp edges with a spoon, or cover them with tape.',
       'Poke holes in the bottom if you will use it as a plant pot.'],
 'FREE', 'LOW'),
('REC_METAL_CANS_FINISH_OPENED_CANS', 'REC_METAL_CANS', 'REDUCE',
 'Finish opened cans before opening another',
 'Plan meals so an opened can is fully used before a second one is opened. Leftover canned food keeps for a day or two in a covered container in the fridge.',
 ARRAY['Move leftovers from an opened can into a covered container and refrigerate them.',
       'Use them in the next meal, like mixing sardines into misua or eggs.',
       'Open a new can only when the last one is finished.'],
 'FREE', 'LOW'),

-- REC_OTHER
('REC_OTHER_REFUSE_REUSE_REFILL', 'REC_OTHER', 'PREVENT',
 'Before buying, ask: skip it, reuse, or refill?',
 'Before buying something packaged, ask three quick questions: can I skip it, reuse something I already own, or get a refill? Even one yes means less to throw away.',
 ARRAY['Pause before paying and ask the three questions.',
       'Check at home for containers or items you can reuse.',
       'Look for refill or takal options at the palengke or sari-sari store.'],
 'FREE', 'LOW'),
('REC_OTHER_KEEP_STURDY_ITEMS', 'REC_OTHER', 'REUSE',
 'Clean and keep sturdy items for storage',
 'Sturdy packaging like tins, tubs, and thick bags can be cleaned and reused to store things at home. Keep only what you will actually use.',
 ARRAY['Clean items right after emptying them.',
       'Keep them in one box so they are easy to find.',
       'Give away extras you do not need.'],
 'FREE', 'LOW'),
('REC_OTHER_NAME_IT', 'REC_OTHER', 'PREVENT',
 'Note what it was so Menosan can suggest more',
 'Next time, give the item a short, specific name and pick the closest subcategory when logging. Menosan can then suggest something that fits better.',
 ARRAY['When logging, write what the item is, like "milk carton" or "foil tray".',
       'Choose the closest subcategory instead of Other when one fits.'],
 'FREE', 'LOW'),

-- RES_SACHETS
('RES_SACHETS_REFILL_STATION', 'RES_SACHETS', 'REDUCE',
 'Bring an old bottle to a refill station',
 'Refill stations sell shampoo, dishwashing liquid, and detergent in small, tingi-sized amounts, poured into your own bottle. You pay for the product, not the sachet.',
 ARRAY['Find a refill station at the palengke, a sari-sari store, or a grocery.',
       'Rinse an old bottle and bring it along.',
       'Buy only the amount you need for the week.'],
 'SAVES_MONEY', 'LOW'),
('RES_SACHETS_TAKAL_COFFEE_SUGAR', 'RES_SACHETS', 'REDUCE',
 'Buy coffee and sugar takal and keep them in jars',
 'Instead of 3-in-1 sachets, buy coffee, sugar, and creamer takal (scooped) at the palengke and keep them in jars at home. You can mix each cup the way you like it.',
 ARRAY['Bring small jars or containers to the palengke.',
       'Ask the vendor for takal coffee, sugar, and creamer.',
       'Mix one cup at home using a spoonful of each.'],
 'SAVES_MONEY', 'LOW'),
('RES_SACHETS_NEXT_SIZE_UP', 'RES_SACHETS', 'REDUCE',
 'If your budget allows, try the next size up',
 'If your budget allows this week, buy the next size up of one product you use every day. Compare the price per use first, since it is often cheaper than many sachets.',
 ARRAY['Pick one everyday product, like shampoo or coffee.',
       'Compare the price per use of the sachet and the bigger pack.',
       'Buy the bigger pack only if it fits this week''s budget.'],
 'SAVES_MONEY', 'MEDIUM'),

-- RES_PLASTIC_BAGS
('RES_PLASTIC_BAGS_BRING_BAG', 'RES_PLASTIC_BAGS', 'PREVENT',
 'Bring a bayong, eco bag, or old sando bag',
 'Bring a bayong, eco bag, or an old sando bag when going to the palengke or sari-sari store. Keeping one by the door makes it easy to remember.',
 ARRAY['Fold a bag and keep it by the door or in your everyday bag.',
       'Hand it to the vendor before they reach for a plastic bag.',
       'Put it back by the door once you unpack.'],
 'FREE', 'LOW'),
('RES_PLASTIC_BAGS_SKIP_FOR_SMALL_ITEMS', 'RES_PLASTIC_BAGS', 'PREVENT',
 'Skip the plastic bag for small items',
 'For small items you can carry or pocket, say "no plastic, thanks". It takes a second and can mean several fewer bags a week.',
 ARRAY['Decide before paying if you really need a bag.',
       'Say "no plastic, thanks" and carry or pocket the item.',
       'Put several small buys in one bag instead of one bag each.'],
 'FREE', 'LOW'),
('RES_PLASTIC_BAGS_REUSE_AS_LINERS', 'RES_PLASTIC_BAGS', 'REUSE',
 'Reuse sando bags as trash liners',
 'Use the sando bags you already get as liners for trash bins instead of buying garbage bags. It saves money and gives each bag a second use.',
 ARRAY['Keep sando bags folded in one spot.',
       'Use them to line small bins in the kitchen and bathroom.',
       'Buy garbage bags only for the large bin, if at all.'],
 'SAVES_MONEY', 'LOW'),

-- RES_SNACK_WRAPPERS
('RES_SNACK_WRAPPERS_HOME_MERIENDA', 'RES_SNACK_WRAPPERS', 'REDUCE',
 'Make simple home merienda a few times a week',
 'Try making simple merienda at home a few times this week: boiled kamote, turon, pandesal, or banana cue. It is often cheaper than packed snacks and leaves no wrappers.',
 ARRAY['Pick 2-3 days this week for home merienda.',
       'Buy kamote, saba, or pandesal on your palengke or bakery trip.',
       'Cook a batch and share it with the household.'],
 'SAVES_MONEY', 'MEDIUM'),
('RES_SNACK_WRAPPERS_BIG_PACK_PORTION', 'RES_SNACK_WRAPPERS', 'REDUCE',
 'Portion a bigger pack into a reusable container',
 'If your budget allows, buy one bigger pack of a snack you already buy and portion it into a reusable container for baon. It usually costs less per serving than small packs.',
 ARRAY['Compare the price per gram of the big pack and the small packs.',
       'Divide the big pack into daily portions in containers you already have.',
       'Seal the rest tightly so it stays crisp.'],
 'SAVES_MONEY', 'LOW'),
('RES_SNACK_WRAPPERS_WATER_AND_FRUIT', 'RES_SNACK_WRAPPERS', 'PREVENT',
 'Keep water and fruit on hand for cravings',
 'Keep a water bottle and some fruit within reach at home, school, or work. When hunger hits, you have a filling option before reaching for a snack pack.',
 ARRAY['Fill a water bottle before leaving the house.',
       'Put fruit like a banana or guava in your bag or on the table.',
       'Reach for these first when you feel like snacking.'],
 'FREE', 'LOW'),

-- RES_STYROFOAM
('RES_STYROFOAM_BRING_BAUNAN', 'RES_STYROFOAM', 'PREVENT',
 'Bring your own baunan for takeout',
 'Bring your own container (baunan) when buying from a carinderia or takeout stall. Most vendors are happy to fill it, and you skip the styro box.',
 ARRAY['Keep a clean baunan with a lid in your bag or at work.',
       'Hand it to the vendor before they pack your order.',
       'Rinse it after eating so it is ready next time.'],
 'FREE', 'LOW'),
('RES_STYROFOAM_DINE_IN', 'RES_STYROFOAM', 'PREVENT',
 'Dine in instead of taking out when you can',
 'When you have a few extra minutes, eat at the carinderia instead of taking food out. Plates are washed and reused, so there is no styro to throw away.',
 ARRAY['Check if you have time to eat there before ordering.',
       'Order for dine-in and eat at the stall.',
       'Take food out only when you really need to.'],
 'FREE', 'LOW'),
('RES_STYROFOAM_DELIVERY_CHOICES', 'RES_STYROFOAM', 'PREVENT',
 'For deliveries, choose no cutlery and less packaging',
 'When ordering delivery, tick "no cutlery" and pick shops that use paper or reusable packaging when you can. Small choices add up over a week.',
 ARRAY['Turn on the no-cutlery option in the delivery app.',
       'Add a note asking for no extra plastic or sauces you will not use.',
       'Favor shops that pack in paper or reusable containers.'],
 'FREE', 'LOW'),

-- RES_DISPOSABLES
('RES_DISPOSABLES_CARRY_SPOON_FORK', 'RES_DISPOSABLES', 'PREVENT',
 'Keep a spoon and fork from home in your bag',
 'Keep a spoon-and-fork set from home in your bag or baon kit. Then you can say no to plastic cutlery whenever you eat out.',
 ARRAY['Wrap a spoon and fork from home in a small cloth or pouch.',
       'Keep it in your bag or baon kit.',
       'Wash it after use and put it back.'],
 'FREE', 'LOW'),
('RES_DISPOSABLES_NO_STRAW', 'RES_DISPOSABLES', 'PREVENT',
 'Skip the straw when ordering drinks',
 'When ordering drinks, say "no straw, thanks". Most drinks are just as easy to sip from the cup or bottle.',
 ARRAY['Say it while ordering, before the straw goes in.',
       'Remind family members when ordering together.'],
 'FREE', 'LOW'),
('RES_DISPOSABLES_BORROW_FOR_HANDAAN', 'RES_DISPOSABLES', 'PREVENT',
 'Borrow plates and glasses for handaan',
 'For handaan or fiestas, borrow plates, glasses, and spoons from neighbors or relatives instead of buying disposables. It saves money, and you can return the favor next time.',
 ARRAY['List how many plates, glasses, and spoons you need.',
       'Ask neighbors and relatives a few days ahead.',
       'Mark borrowed items with tape and return them washed.'],
 'FREE', 'MEDIUM'),

-- RES_TISSUE
('RES_TISSUE_BASAHAN', 'RES_TISSUE', 'REDUCE',
 'Turn old shirts into washable basahan',
 'Cut old shirts into rags (basahan) for wiping spills and cleaning. They go in the regular wash and replace a lot of tissue.',
 ARRAY['Cut old shirts or towels into hand-sized pieces.',
       'Keep a few in the kitchen and dining area.',
       'Wash them with your regular laundry.'],
 'FREE', 'LOW'),
('RES_TISSUE_PANYO', 'RES_TISSUE', 'PREVENT',
 'Carry a small towel or panyo instead of tissue',
 'Carry a small towel or panyo for sweat, hands, and small spills when you go out. It can replace many tissues a day.',
 ARRAY['Keep a clean panyo or face towel in your bag or pocket.',
       'Swap it for a fresh one every day or two.',
       'Wash it with your regular laundry.'],
 'FREE', 'LOW'),
('RES_TISSUE_CLOTH_NAPKINS', 'RES_TISSUE', 'REDUCE',
 'Use cloth napkins at the table at home',
 'Use cloth table napkins at home that go in the regular wash. Old pillowcases or shirts cut into squares work fine.',
 ARRAY['Cut old cloth into napkin-sized squares.',
       'Put a few on the table at mealtimes.',
       'Wash them with your regular laundry.'],
 'FREE', 'LOW'),

-- RES_DIAPERS_SANITARY
('RES_DIAPERS_SANITARY_LAMPIN_DAYTIME', 'RES_DIAPERS_SANITARY', 'REDUCE',
 'Use cloth lampin at home during the day',
 'When practical, use cloth lampin at home during the day and keep disposables for outings and nights. Even a few cloth changes a day saves money.',
 ARRAY['Start with a few daytime changes when you are at home.',
       'Keep a covered pail of water for used lampin until wash time.',
       'Keep disposables for nights, outings, and busy days.'],
 'SAVES_MONEY', 'MEDIUM'),
('RES_DIAPERS_SANITARY_CLOTH_PADS', 'RES_DIAPERS_SANITARY', 'REDUCE',
 'If comfortable, try washable cloth pads',
 'If you are comfortable with it, try washable cloth pads on some days of your period. They can be sewn from soft old cloth.',
 ARRAY['Sew a few pads from soft, absorbent old cloth, like cotton shirts.',
       'Try them at home first, on lighter days.',
       'Rinse them in cold water, then wash with soap and dry in the sun.'],
 'FREE', 'MEDIUM'),
('RES_DIAPERS_SANITARY_CHANGE_ON_ROUTINE', 'RES_DIAPERS_SANITARY', 'REDUCE',
 'Change diapers on a routine, not just in case',
 'Changing diapers on a routine, and whenever needed, rather than "just in case" can mean fewer diapers a day. Only do this while it stays comfortable for the baby.',
 ARRAY['Notice how often your baby usually needs a change.',
       'Change at those times and whenever the diaper is wet or soiled.',
       'Go back to more frequent changes if you see any rash or discomfort.'],
 'SAVES_MONEY', 'LOW'),

-- RES_OTHER
('RES_OTHER_REFUSE_REUSE_REFILL', 'RES_OTHER', 'PREVENT',
 'Before buying, ask: skip it, reuse, or refill?',
 'Before buying something packaged, ask three quick questions: can I skip it, reuse something I already own, or get a refill? Even one yes means less to throw away.',
 ARRAY['Pause before paying and ask the three questions.',
       'Check at home for containers or items you can reuse.',
       'Look for refill or takal options at the palengke or sari-sari store.'],
 'FREE', 'LOW'),
('RES_OTHER_KEEP_STURDY_PACKAGING', 'RES_OTHER', 'REUSE',
 'Keep sturdy packaging for storage or baon',
 'Sturdy packaging like thick pouches, tins, and trays can be cleaned and reused for storage or baon. Keep only what you will actually use.',
 ARRAY['Clean packaging right after emptying it.',
       'Keep it in one box so it is easy to find.',
       'Give away extras you do not need.'],
 'FREE', 'LOW'),
('RES_OTHER_NAME_IT', 'RES_OTHER', 'PREVENT',
 'Note what it was so Menosan can suggest more',
 'Next time, give the item a short, specific name and pick the closest subcategory when logging. Menosan can then suggest something that fits better.',
 ARRAY['When logging, write what the item is, like "rubber gloves" or "foil pack".',
       'Choose the closest subcategory instead of Other when one fits.'],
 'FREE', 'LOW');
